name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wesleydocke/docker-image-autobuild:latest
    - name: Push the Docker image
    - run : docker login -u wesleydocke -p ${{ secrets.DOCKER_TOKEN }} && docker push wesleydocke/docker-image-autobuild:latest
